# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Travel to Japan Concierge
email: tjconciergeorg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Community to support planning more attractive travel to Japan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tjconcierge.org" # the base hostname & protocol for your site
twitter_username: tjconcierge
github_username:  tjconcierge
facebook_username: tjconcierge

# Build settings
markdown: kramdown
exclude: [vendor]
